name: Style-Free Audio Player
markdown: kramdown
hightlighter: rouge
kramdown:
  auto_ids: false
description: A lightweight wrapper for HTML audio. Bring your own markup and CSS.
url: http://picobel.dev # Local
# url: http://tomhazledine.com/audio/ # Live
exclude: [config.rb,
          gruntfile.js,
          root.css,
          sass,
          favicon_sizes,
          social_icons,
          package.json,
          notes*.md,
          img/design_files*,
          img/raw*,
          node_modules]